/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supportsystem.view;

import java.io.File;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import supportsystem.createXML.LerValoresXML;
import supportsystem.dao.ClienteDAO;
import supportsystem.dao.ClienteDTO;
import supportsystem.dao.ProdutoDAO;
import supportsystem.dao.ProdutoDTO;
import supportsystem.dao.VendedorDAO;
import supportsystem.dao.VendedorDTO;
import supportsystem.logging.LogController;
import supportsystem.models.Cliente;
import supportsystem.models.Produto;
import supportsystem.models.Vendedor;

/**
 *
 * @author Bruno
 */
public class DelVendedor extends javax.swing.JFrame {

    /**
     * Creates new form CadCliente
     */
    public DelVendedor() {
        initComponents();
    }

     /**
     * Creates new form CadCliente
     */
    private Vendedor vendedor;
    

    public int idVendedor;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnGerarXML1 = new javax.swing.JButton();
        cbxNomeprodutoDel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGerarXML = new javax.swing.JButton();
        cbxNomeVendedorDel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        btnGerarXML1.setText("Sim");
        btnGerarXML1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarXML1ActionPerformed(evt);
            }
        });

        cbxNomeprodutoDel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxNomeprodutoDelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxNomeprodutoDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomeprodutoDelActionPerformed(evt);
            }
        });

        jLabel4.setText("Deseja deletar o(a) Produto:");

        jLabel5.setText("?");

        jButton7.setText("Não");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SupportSystem - Cadastro de Produtos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Deletar Vendedor");

        btnGerarXML.setText("Sim");
        btnGerarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarXMLActionPerformed(evt);
            }
        });

        cbxNomeVendedorDel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxNomeVendedorDelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxNomeVendedorDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomeVendedorDelActionPerformed(evt);
            }
        });

        jLabel6.setText("Deseja deletar o(a) Vendedor:");

        jLabel7.setText("?");

        jButton8.setText("Não");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxNomeVendedorDel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnGerarXML, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(cbxNomeVendedorDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(btnGerarXML))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarXMLActionPerformed
        try {
            Vendedor vendedor = new Vendedor();
            VendedorDAO vendedorDAO = new VendedorDAO();

            vendedor.setId_vendedor(idVendedor);

            
            
            if (vendedorDAO.deleteVendedor(vendedor)) {
            JOptionPane.showMessageDialog(null, "Vendedor deletado com sucesso!");
            LogController.createLog("Vendedor deletado", "I");
            } else {
            LogController.createLog("Erro ao deletar vendedor", "W");
            JOptionPane.showMessageDialog(null, "Erro ao deletar o vendedor!");
            }
        } catch (SQLException ex) {
        }

    }//GEN-LAST:event_btnGerarXMLActionPerformed

    private void btnGerarXML1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarXML1ActionPerformed

    }//GEN-LAST:event_btnGerarXML1ActionPerformed

    private void cbxNomeprodutoDelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxNomeprodutoDelAncestorAdded

    }//GEN-LAST:event_cbxNomeprodutoDelAncestorAdded

    private void cbxNomeprodutoDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomeprodutoDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNomeprodutoDelActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cbxNomeVendedorDelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxNomeVendedorDelAncestorAdded
        cbxNomeVendedorDel.setEditable(false);
        cbxNomeVendedorDel.removeAll();
        Object selectedItem = idVendedor;
        if (selectedItem != null) {
            int vendedorid = idVendedor;

            VendedorDTO vendedordto = new VendedorDTO();
            
            VendedorDAO vendedordao = new VendedorDAO();

            try {
                Vendedor Vvendedor = vendedordao.buscarVendedor(vendedorid);
                this.vendedor = Vvendedor;
                PopulateFields(Vvendedor);
                //cbxNomeClienteatual.();
                
            } catch (SQLException ex) {
                //Logger.getLogger(InserirVenda.class.getName()).log(Level.SEVERE, null, ex);
            };
        }
    }//GEN-LAST:event_cbxNomeVendedorDelAncestorAdded

    private void cbxNomeVendedorDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomeVendedorDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNomeVendedorDelActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelVendedor().setVisible(true);
            }
        });
        
        
    }
    private void PopulateFields(Vendedor Vvendedor){
        cbxNomeVendedorDel.setText(Vvendedor.getNome_vendedor());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarXML;
    private javax.swing.JButton btnGerarXML1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cbxNomeVendedorDel;
    private javax.swing.JTextField cbxNomeprodutoDel;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
