/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supportsystem.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import supportsystem.dao.ClienteDAO;
import supportsystem.dao.ClienteDTO;
import supportsystem.dao.ProdutoDAO;
import supportsystem.dao.ProdutoDTO;
import supportsystem.dao.VendedorDAO;
import supportsystem.dao.VendedorDTO;
import supportsystem.logging.LogController;
import supportsystem.models.Cliente;
import supportsystem.models.Produto;
import supportsystem.models.Vendedor;

/**
 *
 * @author Bruno
 */
public class EditProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadCliente
     */
    private Produto produto;
    
    public EditProduto() {
        initComponents();
    }

    public int idProduto;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxNovoNomeProduto = new javax.swing.JTextField();
        btnEditCliente = new javax.swing.JButton();
        cbxNomeVendedoratual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxNovoPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Editar Produto");

        jLabel2.setText("Novo Nome:");

        cbxNovoNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNovoNomeProdutoActionPerformed(evt);
            }
        });

        btnEditCliente.setText("Editar");
        btnEditCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClienteActionPerformed(evt);
            }
        });

        cbxNomeVendedoratual.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxNomeVendedoratualAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxNomeVendedoratual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomeVendedoratualActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome atual:");

        cbxNovoPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNovoPrecoActionPerformed(evt);
            }
        });
        cbxNovoPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbxNovoPrecoKeyTyped(evt);
            }
        });

        jLabel5.setText("Novo Preço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxNovoNomeProduto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxNovoPreco))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxNomeVendedoratual, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnEditCliente)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbxNomeVendedoratual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxNovoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbxNovoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnEditCliente)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClienteActionPerformed
        try {
            Produto produto = new Produto();
            ProdutoDAO produtoDAO = new ProdutoDAO();

            produto.setId_item(idProduto);
            produto.setNome_item(cbxNovoNomeProduto.getText());
            produto.setPreco(Integer.parseInt(cbxNovoPreco.getText()));
            
            produtoDAO.editarProduto(produto);
            JOptionPane.showMessageDialog(null, "Produto editado com sucesso!");

        } catch (SQLException ex) {
            LogController.createLog("Erro ao cadastrar produto", "W");
        }
        LogController.createLog("Produto cadastrado", "I");
    }//GEN-LAST:event_btnEditClienteActionPerformed

    private void cbxNomeVendedoratualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomeVendedoratualActionPerformed
        
    }//GEN-LAST:event_cbxNomeVendedoratualActionPerformed

    private void cbxNomeVendedoratualAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxNomeVendedoratualAncestorAdded
        cbxNomeVendedoratual.setEditable(false);
        cbxNomeVendedoratual.removeAll();
        Object selectedItem = idProduto;
        if (selectedItem != null) {
            int produtoid = idProduto;

            ProdutoDTO produtodto = new ProdutoDTO();
            
            ProdutoDAO produtodao = new ProdutoDAO();

            try {
                Produto Pproduto = produtodao.buscarProduto(produtoid);
                this.produto = Pproduto;
                PopulateFields(Pproduto);
                //cbxNomeClienteatual.();
                
            } catch (SQLException ex) {
                //Logger.getLogger(InserirVenda.class.getName()).log(Level.SEVERE, null, ex);
            };
        }
        
    }//GEN-LAST:event_cbxNomeVendedoratualAncestorAdded

    private void cbxNovoPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNovoPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNovoPrecoActionPerformed

    private void cbxNovoPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxNovoPrecoKeyTyped
    char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        } 
    }//GEN-LAST:event_cbxNovoPrecoKeyTyped

    private void cbxNovoNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNovoNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNovoNomeProdutoActionPerformed

    private void PopulateFields(Produto Pproduto){
        cbxNomeVendedoratual.setText(Pproduto.getNome_item());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditCliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cbxNomeVendedoratual;
    private javax.swing.JTextField cbxNovoNomeProduto;
    private javax.swing.JTextField cbxNovoPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
