/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supportsystem.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import supportsystem.dao.ClienteDAO;
import supportsystem.dao.ClienteDTO;
import supportsystem.dao.ProdutoDAO;
import supportsystem.logging.LogController;
import supportsystem.models.Cliente;
import supportsystem.models.Produto;

/**
 *
 * @author Bruno
 */
public class EditCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadCliente
     */
    private Cliente cliente;
    
    public EditCliente() {
        initComponents();
    }

    public int idCliente;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxNomeCliente = new javax.swing.JTextField();
        btnEditCliente = new javax.swing.JButton();
        rbtnTipoPf = new javax.swing.JRadioButton();
        rbtnTipoPj = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cbxNomeClienteatual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Editar Cliente");

        jLabel2.setText("Novo nome:");

        btnEditCliente.setText("Editar");
        btnEditCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTipoPf);
        rbtnTipoPf.setText("PF");
        rbtnTipoPf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTipoPfActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTipoPj);
        rbtnTipoPj.setText("PJ");

        jLabel3.setText("Tipo:");

        cbxNomeClienteatual.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxNomeClienteatualAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxNomeClienteatual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomeClienteatualActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome atual:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnEditCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(13, 13, 13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnTipoPf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnTipoPj))
                                    .addComponent(cbxNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cbxNomeClienteatual, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxNomeClienteatual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTipoPf)
                    .addComponent(rbtnTipoPj)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnEditCliente)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClienteActionPerformed
        try {
            Cliente cliente = new Cliente();
            ClienteDAO clienteDao = new ClienteDAO();

            cliente.setId_cliente(idCliente);
            cliente.setNome_cliente(cbxNomeCliente.getText());
            if (rbtnTipoPf.isSelected()) {
                cliente.setId_tipo_cliente(1);
            } else if (rbtnTipoPj.isSelected()) {
                cliente.setId_tipo_cliente(2);
            }
            
            if (cliente.getNome_cliente().isEmpty()) {
                JOptionPane.showMessageDialog(null, "É necessario inserir o novo nome e tipo para o cliente!");
            }else{
                JOptionPane.showMessageDialog(null, "Cliente editado com sucesso!");
            }
            clienteDao.editarCliente(cliente);
        } catch (SQLException ex) {
            LogController.createLog("Erro ao cadastrar cliente", "W");
        }
        
        LogController.createLog("Cliente cadastrado", "I");
    }//GEN-LAST:event_btnEditClienteActionPerformed

    private void rbtnTipoPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTipoPfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTipoPfActionPerformed

    private void cbxNomeClienteatualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomeClienteatualActionPerformed
        
    }//GEN-LAST:event_cbxNomeClienteatualActionPerformed

    private void cbxNomeClienteatualAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxNomeClienteatualAncestorAdded
        cbxNomeClienteatual.setEditable(false);
        cbxNomeClienteatual.removeAll();
        Object selectedItem = idCliente;
        if (selectedItem != null) {
            int clienteid = idCliente;

            ClienteDTO clientedto = new ClienteDTO();
            
            ClienteDAO clientedao = new ClienteDAO();

            try {
                Cliente Ccliente = clientedao.buscarCliente(clienteid);
                this.cliente = Ccliente;
                PopulateFields(Ccliente);
                //cbxNomeClienteatual.();
                
            } catch (SQLException ex) {
                //Logger.getLogger(InserirVenda.class.getName()).log(Level.SEVERE, null, ex);
            };
        }
        
    }//GEN-LAST:event_cbxNomeClienteatualAncestorAdded

    private void PopulateFields(Cliente Ccliente){
        cbxNomeClienteatual.setText(Ccliente.getNome_cliente());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditCliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cbxNomeCliente;
    private javax.swing.JTextField cbxNomeClienteatual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtnTipoPf;
    private javax.swing.JRadioButton rbtnTipoPj;
    // End of variables declaration//GEN-END:variables

}
